# Generated by Django 3.2.6 on 2021-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Favoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('business_id', models.CharField(default='DEFAULT VALUE', max_length=140)),
            ],
        ),
    ]
